# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fbbdc3027fc3f6c62fda4d90486718428b70d374ae93698f6c86101e6dd0be890ac173ef65332087e5a85638e595569ead86e814d69958c51fc3779509c67c2

test:
  secret_key_base: 9ebfdbf3007125c61f2a1dc170c5fcc66fe302d1817831717f57d50a8711cfd84c002275bc31c4fd47eaa93c8bf1c6f981da249efdac1f71a8707f7e639faba8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
